name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Prepare build
      run: chmod +x ./compilation/build.sh
    - name: Build
      run: ./compilation/build.sh
    - name: Prepare testing
      run: chmod +x ./grading/test.sh
    - name: Test preview
      run: ./grading/test.sh -m grading/group1.txt -t 5 -l 64
    - name: n<15 (20 pts.)
      id: n-15-20-pts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: n<15 (20 pts.)
        command: "./grading/test.sh -m grading/group1.txt -t 0.1 -l 64"
        timeout: 1
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        N-15-20-PTS_RESULTS: "${{steps.n-15-20-pts.outputs.result}}"
      with:
        runners: n-15-20-pts
